name: PHPUnit ig
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    
    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      with:
        version: 9.6.11
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml
        php_extensions: xdebug gd
        coverage_cobertura: coverage.cobertura.xml
      env:
        XDEBUG_MODE: coverage

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.cobertura.xml
        thresholds: '51 75'
    
    - name: PHP Code Sniffer
      uses: php-actions/phpcs@v1
      with:
        php_version: 8.0
        path: lib/
        standard: PSR2
        error_severity : 0
        warning_severity : 8

    - name: PHP Mess Detector
      uses: php-actions/phpmd@v1
      with:
        php_version: 8.0
        path: lib/
        output: text

    - name: PHP Static Analysis
      uses: php-actions/phpstan@v3
      with:
        path: lib/